# Generated by Django 4.1.7 on 2023-06-27 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('id_number', models.CharField(max_length=8)),
                ('license_no', models.CharField(max_length=12)),
                ('groups', models.ManyToManyField(related_name='driver_accounts', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='driver_accounts', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('pickup', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('ride_description', models.CharField(max_length=500)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('travel_date', models.DateTimeField()),
                ('passengers_no', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('vehicle_model', models.CharField(max_length=20)),
                ('vehicle_condition', models.CharField(choices=[('new', 'New'), ('old', 'Old'), ('partially_new', 'Partially New'), ('partially_old', 'Partially Old')], max_length=20)),
                ('plate_number', models.CharField(max_length=8)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('drivername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_rides', to='drivers.driveraccount')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
